import Foundation
import SQLiteData

/// A small piece of text living inside a ``Vault``.
///
/// A `Thing` has a single foreign key (`vaultID`), so when its parent ``Vault``
/// is shared it is shared along with it.
@Table
public struct Thing: Identifiable, Equatable, Sendable {
    public let id: UUID
    public var vaultID: Vault.ID
    public var text: String = ""
    /// Fractional order key for manual ordering within a vault (lower sorts
    /// first). A lexicographic base-62 string generated by ``FractionalIndex``
    /// so that inserting or moving a thing rewrites only its own key — never its
    /// neighbors — which keeps ordering robust under iCloud sync. Always tie-break
    /// with `id` when ordering (`ORDER BY rank, id`).
    public var rank: String = ""
    /// Set from the `\.date.now` dependency at write time. Defaults to a
    /// referentially-transparent sentinel rather than a live `Date()`.
    /// Also avoids the iCloud-reserved column name `modificationDate`.
    public var updatedAt: Date = .distantPast
}

extension Thing.Draft: Equatable {}

// All of Draft's members (UUID?, UUID, String, Date) are Sendable value types,
// so the generated `Draft` is safe to send across concurrency domains —
// e.g. captured in a `.run` effect to be saved. The `@Table` macro does not add
// this for us.
extension Thing.Draft: Sendable {}
